#DB_HOST: localhost
#DB_PORT: 5432
#DB_NAME: wishlist
#DB_USERNAME: postgres
#DB_PASSWORD: your_password

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: spring-app

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update